"""Blob -> plan for the PreStage's MiniMax H3 branch: one still, generated by
the video model.

The other two pre-stage architectures are image models and are compiled by
`compile_image.py`. This one is not: H3 is the video model the rest of the pack
already loads, and a still from it is *a video generation whose first latent
frame is decoded as a picture*. So this module compiles a pre-stage blob into
exactly the request shape `compile.compile_request` already takes, and the
render path reuses the video segment node verbatim — same conditioning, same
reference ordering, same LoRA routing, same checkpoints.

**Why the first latent frame is a still at all.** The H3 VAE is causal on the
17k+5 <-> 5k+2 grid: a 5-frame clip has two latent frames, and the first of them
is a function of frame 0 alone. Encoding a single image produces that same
one-frame latent (core's `downscale_ratio` returns 1 for a single frame), which
is what the experimental T=1 image decoder was trained against. Decoding latent
index 0 is therefore not a trick — it is the one temporal slice the image VAE
was fitted to.

**What is still unknown, and what the dev block is for.** The DiT's trained
range is 124-362 frames (`canvas.TRAINED_MIN_FRAMES`), so a 5-frame generation
is far off-distribution temporally even though the *latent* it produces is in
distribution spatially. Whether the shortest legal clip gives a still as good as
a full-length one — and whether the frozen-encoder image VAE beats the stock H3
VAE at decoding it — is a question about weights, not about code, so the `dev`
block sweeps lengths, latent indices and VAE files in one queue and saves each
combination under its own name. It is scaffolding: see `DEV_*` below, all of
which comes out once the numbers are in.

Pure, like its two neighbours: no torch, no ComfyUI, no disk. The canvas and
duration rules are `canvas.py`'s, because they are the video model's.
"""

from dataclasses import dataclass

from . import canvas
from .compile import CHECKPOINTS, CompileError, active_loras, collect_triggers

ARCH = "minimax"

# The shortest legal clip: 5 frames, two latent frames, the cheapest sampler
# pass H3 can be asked for. The default because a still only needs the first
# latent frame and everything past it is paid for and thrown away.
DEFAULT_FRAMES = 5

# What the length pill offers. Every one is a legal 17n+5 count; the top of the
# list is the bottom of the trained range, so the pill spans "cheapest possible"
# to "what the weights actually saw".
STILL_LENGTHS = (5, 22, 39, 56, 90, 124)

# Which latent frame is decoded. 0 is the causal first frame — the slice the
# image VAE was trained on. Negative indexes from the end, so -1 is the last
# frame of the clip and is how you ask for "the shot a moment later".
DEFAULT_LATENT_INDEX = 0

# How the prompt reaches the DiT. "context-ir" is what a video render does: the
# shot description is composed into the model's documented Context-IR form,
# duration line and all. "plain" sends the typed sentence verbatim through
# `prompt_override`, which is the same escape hatch the refiner uses — worth
# having because a Context-IR block describes a 0.21-second video, and whether
# that helps or hurts a still is exactly the kind of thing only a render says.
PROMPT_MODES = ("context-ir", "plain")
DEFAULT_PROMPT_MODE = "context-ir"


def latent_frames(frames):
    """Frames -> how many latent frames the VAE packs them into.

    Mirror of core's `nodes_minimax_h3.video_latent_t`, kept here so an index
    can be refused before anything is queued. 5 -> 2, 22 -> 5, 124 -> 25.
    """
    return 2 if frames <= 5 else ((frames - 5) // 17) * 5 + 2


def resolve_index(index, frames):
    """A latent index (possibly negative) -> a real one, or refuse it."""
    total = latent_frames(frames)
    resolved = index if index >= 0 else total + index
    if not 0 <= resolved < total:
        raise CompileError(
            f"latent frame {index} does not exist in a {frames}-frame clip — "
            f"it packs into {total} latent frames (0..{total - 1})"
        )
    return resolved


@dataclass(frozen=True)
class Decode:
    """One picture taken off one sampler pass.

    `vae` is a filename when this decode overrides the picked VAE, which only
    the dev sweep does; `None` means the file the node is set to.
    """

    index: int
    vae: str = None
    label: str = ""


@dataclass(frozen=True)
class StillPass:
    """One sampler pass, and everything decoded out of it."""

    frames: int
    request: dict
    prompt_override: str = None
    decodes: tuple = ()

    @property
    def payload(self):
        """The segment payload — the same shape `MiniMaxH3Creator` builds."""
        payload = {"request": self.request, "continue": False, "continue_audio": False}
        if self.prompt_override:
            payload["prompt_override"] = self.prompt_override
        return payload


@dataclass(frozen=True)
class StillPlan:
    passes: tuple = ()
    # Whether anything attached will be encoded as sound. False for almost every
    # still, and that is what leaves the audio VAE unloaded.
    audio: bool = False
    # True when the dev block widened this into a sweep, which is the one case
    # a single pre-stage queue writes more than one file.
    sweeping: bool = False

    @property
    def images(self):
        return sum(len(one.decodes) for one in self.passes)


# What a reference entry may carry beyond its handle, kind and filename. These
# are `compile._parse_assets`'s own fields, passed through rather than re-read:
# a still cites a face, a clip's motion or a soundtrack exactly as a shot does.
REF_FIELDS = ("track", "ref_size", "takes", "trim")


def _assets(data):
    """The pre-stage's keyframes and references, as video-side asset dicts.

    The pre-stage keeps its keyframes in two fields of their own where the
    Creator keeps one flat list; this is where the two vocabularies meet, and it
    is the only difference between them. Everything a shot can attach, a still
    can attach: nine reference images, three reference videos, three audio
    clips, a start frame, an end frame. The limits, the ordering and the
    `<Picture N>` / `<Video N>` / `<Audio N>` numbering are all
    `compile.compile_request`'s, because a still *is* one of those requests.

    An init image is a start frame rather than an img2img source: H3's image
    conditioning is a keyframe, pinned and re-injected every step, and it has no
    denoise to trade against.
    """
    assets = []

    # Keyframes take img-N handles rather than a scheme of their own, so a
    # prompt cites them the way a Creator prompt does. Numbered around whatever
    # the references already hold: H3 refuses keyframes and references in one
    # generation, and that refusal is worth hearing instead of a handle clash.
    taken = {item.get("handle") for item in data.get("refs") or [] if isinstance(item, dict)}

    def free_handle():
        for n in range(1, 100):
            if f"img-{n}" not in taken:
                taken.add(f"img-{n}")
                return f"img-{n}"
        raise CompileError("too many attachments to name")

    for field, role in (("init", "first_frame"), ("end", "last_frame")):
        entry = data.get(field)
        if entry is None:
            continue
        if not isinstance(entry, dict) or not entry.get("filename"):
            raise CompileError(f"the {role.replace('_', ' ')} entry must carry a filename")
        assets.append({"handle": entry.get("handle") or free_handle(), "kind": "image",
                       "role": role, "filename": entry["filename"]})

    for item in data.get("refs") or []:
        filename = item.get("filename") if isinstance(item, dict) else item
        if not filename or not isinstance(filename, str):
            raise CompileError("every reference must carry a filename")
        item = item if isinstance(item, dict) else {}
        kind = item.get("kind") or "image"
        entry = {"handle": item.get("handle") or f"{kind[:3]}-{len(assets) + 1}",
                 "kind": kind, "role": "reference", "filename": filename}
        for key in REF_FIELDS:
            if item.get(key) is not None:
                entry[key] = item[key]
        assets.append(entry)

    return assets


def needs_audio(assets):
    """Whether this still will reach for the audio VAE.

    A reference audio clip, or a reference video cited for its soundtrack. Most
    stills touch neither, and a loader in the graph is a file loaded whether or
    not anything reads it — so this is what decides that the audio VAE is
    required at all.
    """
    for asset in assets:
        if asset.get("role") != "reference":
            continue
        if asset.get("kind") == "audio":
            return True
        if asset.get("kind") == "video" and asset.get("track") in ("picture+sound", "sound"):
            return True
    return False


def _pin(block):
    """The user's checkpoint pin, or "auto". `compile._resolve_checkpoint` owns
    which pins are legal against which mode; this only refuses a typo."""
    pin = block.get("checkpoint") or "auto"
    if pin != "auto" and pin not in CHECKPOINTS:
        raise CompileError(f"unknown checkpoint pin {pin!r}")
    return pin


def _checkpoint(pin, assets):
    """Which H3 checkpoint this still will route to.

    The same derivation `_resolve_checkpoint` makes, needed here only so the
    plain-prompt branch can collect the trigger words of the LoRAs that will
    actually be patched on. The authoritative answer is still the compiled
    request's, which is what the render path reads.
    """
    if pin != "auto":
        return pin
    return "ref2va" if any(a["role"] == "reference" for a in assets) else "fl2va"


def _frames(raw):
    """A requested frame count -> the legal 17n+5 count actually generated."""
    try:
        frames = int(raw)
    except (TypeError, ValueError):
        raise CompileError("the still length must be a whole number of frames")
    return canvas.frames_for_seconds(max(1, frames) / canvas.FPS)


def _block(data):
    block = data.get(ARCH)
    return block if isinstance(block, dict) else {}


def _request(data, assets, pin, frames):
    """The creator-shaped request one pass generates from."""
    aspect = data.get("aspect", "16:9")
    if aspect not in canvas.ASPECT_PRESETS:
        raise CompileError(f"unknown aspect ratio {aspect!r}")

    request = {
        "prompt": str(data.get("prompt") or "").strip(),
        "assets": assets,
        "loras": data.get("loras") or [],
        # The duration the video side speaks in. Snapped already, so
        # `frames_for_seconds` inside `compile_request` lands back on `frames`.
        "duration_s": canvas.seconds_for_frames(frames),
        "aspect": aspect,
        "short_edge": data.get("short_edge", canvas.NATIVE_SHORT_EDGE),
    }
    if pin != "auto":
        request["checkpoint"] = pin
    return request


def _plain_prompt(data, assets, checkpoint):
    """The typed sentence, trigger words in front, and nothing composed.

    Same construction as the video body's prefix — a word only counts if its
    LoRA is actually in this run — because that is the one part of the composed
    prompt an override would otherwise drop on the floor.
    """
    prompt = str(data.get("prompt") or "").strip()
    triggers = collect_triggers(active_loras(data.get("loras"), checkpoint))
    if triggers:
        prompt = f"{', '.join(triggers)}, {prompt}" if prompt else ", ".join(triggers)
    return prompt


# ---- dev sweep ---------------------------------------------------------------
#
# DEV: everything from here to `compile_still` is scaffolding for choosing the
# still length, the latent index and the decoder, and comes out with the
# `dev` block once those are settled. It adds nothing to a normal render: an
# absent or empty block compiles to exactly one pass with exactly one decode.

DEV_KEY = "dev"
# How many pictures one queue may expand into. A sweep is lengths x indices x
# VAEs and the lengths are sampler passes, so this is the difference between a
# long experiment and a hung machine.
DEV_MAX_PASSES = 8
DEV_MAX_IMAGES = 64


def _dev(data):
    block = _block(data).get(DEV_KEY)
    return block if isinstance(block, dict) else {}


def _dev_list(block, key, cast):
    raw = block.get(key)
    if not isinstance(raw, (list, tuple)):
        return []
    out = []
    for item in raw:
        try:
            value = cast(item)
        except (TypeError, ValueError):
            raise CompileError(f"the dev sweep's {key} list holds an unusable entry {item!r}")
        if value not in out:
            out.append(value)
    return out


def _label(frames, index, vae):
    """What a swept file is called, appended to the output prefix.

    The name has to carry the whole coordinate or the sweep is a folder of
    pictures nobody can tell apart.
    """
    parts = [f"L{frames}", f"i{index}"]
    if vae:
        stem = vae.replace("\\", "/").rsplit("/", 1)[-1].rsplit(".", 1)[0]
        parts.append("".join(c if c.isalnum() or c in "-_" else "-" for c in stem)[:40])
    return "_".join(parts)


def compile_still(data):
    """A pre-stage blob (arch 'minimax') -> `StillPlan`.

    Deep validation is deliberately not repeated here: the segment node compiles
    the request it is handed, exactly as it does for a Creator render, so the
    canvas, the mode and the reference plan are worked out in one place. What
    this refuses is what would otherwise fail late or silently — an empty
    prompt, a reference kind a still cannot use, an impossible latent index.
    """
    if not isinstance(data, dict):
        raise CompileError("prestage_data must be a JSON object")
    if not str(data.get("prompt") or "").strip():
        raise CompileError("describe the image first — the prompt is empty")

    block = _block(data)
    assets = _assets(data)
    pin = _pin(block)
    checkpoint = _checkpoint(pin, assets)

    mode = block.get("prompt_mode", DEFAULT_PROMPT_MODE)
    if mode not in PROMPT_MODES:
        raise CompileError(f"unknown prompt mode {mode!r}")
    override = _plain_prompt(data, assets, checkpoint) if mode == "plain" else None

    frames = _frames(block.get("frames", DEFAULT_FRAMES))
    index = block.get("latent_index", DEFAULT_LATENT_INDEX)
    try:
        index = int(index)
    except (TypeError, ValueError):
        raise CompileError("the latent frame index must be a whole number")

    dev = _dev(data)                                            # DEV
    lengths = _dev_list(dev, "lengths", int) or [frames]        # DEV
    lengths = [_frames(one) for one in lengths]                 # DEV
    indices = _dev_list(dev, "indices", int) or [index]         # DEV
    vaes = _dev_list(dev, "vaes", str) or [None]                # DEV
    sweeping = len(lengths) * len(indices) * len(vaes) > 1      # DEV

    if len(lengths) > DEV_MAX_PASSES:                           # DEV
        raise CompileError(
            f"a sweep runs at most {DEV_MAX_PASSES} lengths — each one is a whole "
            f"sampler pass"
        )
    if len(lengths) * len(indices) * len(vaes) > DEV_MAX_IMAGES:  # DEV
        raise CompileError(f"a sweep writes at most {DEV_MAX_IMAGES} pictures")

    passes = []
    for length in lengths:
        decodes = []
        for one in indices:
            resolved = resolve_index(one, length)
            for vae in vaes:
                decodes.append(Decode(
                    index=resolved, vae=vae,
                    label=_label(length, one, vae) if sweeping else ""))
        passes.append(StillPass(
            frames=length,
            request=_request(data, assets, pin, length),
            prompt_override=override,
            decodes=tuple(decodes)))

    return StillPlan(passes=tuple(passes), audio=needs_audio(assets), sweeping=sweeping)
